@startuml

skinparam actorStyle awesome

actor Customer
participant AirlineWebsite
participant CheckInAPI
database BookingDatabase

Customer -> AirlineWebsite: enter booking ref. and last name 
AirlineWebsite -> AirlineWebsite: validate input
AirlineWebsite -> CheckInAPI: retrieve matching booking (search criteria)
CheckInAPI -> BookingDatabase: locate booking(ref., dates etc)
BookingDatabase --> CheckInAPI: matching booking
CheckInAPI --> AirlineWebsite: matching booking
AirlineWebsite --> Customer: matching booking
Customer -> AirlineWebsite: enter passport number and number of bags
AirlineWebsite -> AirlineWebsite: validate passport number
AirlineWebsite --> CheckInAPI: send passport number and baggage count
CheckInAPI -> BookingDatabase: store passport number and baggage count
Customer -> AirlineWebsite: select seat(s)
AirlineWebsite -> AirlineWebsite: validate seat availability
AirlineWebsite --> CheckInAPI: send seat number(s)
CheckInAPI -> BookingDatabase: reserve/assign seat(s)
BookingDatabase --> CheckInAPI: booking summary
CheckInAPI --> AirlineWebsite: booking summary generates boarding pass
AirlineWebsite --> Customer: confirm check-in and send boarding pass

@enduml

' purchase additional luggage allowance
' purchase aditional leg room
' purchase insurance