@startuml

skinparam actorStyle awesome

left to right direction

actor Customer
package Maintenance {
    actor MaintenancePersonnel as m
}
package StationAllocator {
    actor StationAllocator as s
}


rectangle ScooterApp {
usecase Register
usecase Hire
usecase Ride
usecase ReturnToDock
usecase TakePayment
usecase Abandon
usecase NotifyRepair
' rectangle Maintenance {
usecase RetrieveFaultCode
usecase ArrangeRepair
usecase Repair
usecase MakeAvailable
' rectangle Maintenance {
' usecase NotifyAbandonedScooter
usecase NotifyDistribution
usecase CollectScooter

Customer --> Register
Customer --> Hire
Customer --> Ride
Customer --> Abandon
Customer --> ReturnToDock
Customer --> NotifyRepair

Maintenance <-- NotifyRepair
Maintenance --> RetrieveFaultCode
Maintenance --> ArrangeRepair
Maintenance --> Repair
Maintenance --> ReturnToDock
Maintenance --> MakeAvailable

StationAllocator <-- NotifyDistribution
StationAllocator <-- Abandon
StationAllocator --> CollectScooter
StationAllocator --> ReturnToDock

ReturnToDock -> TakePayment
}
@enduml